=== habyb/Java-Advanced/XMLValidateDOM/users.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.elasticconcept.com/java/xml"
	xmlns="http://www.elasticconcept.com/java/xml">
	
	<xsd:element name="name">
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:minLength value="1" />
				<xsd:maxLength value="30" />
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>
	
	<xsd:element name="age" type="xsd:integer" />
	<xsd:element name="email" type="xsd:string" />
	
	<xsd:element name="user">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="name" minOccurs="1" maxOccurs="1" />
				<xsd:element ref="age" minOccurs="1" maxOccurs="1" />
				<xsd:element ref="email" minOccurs="1" maxOccurs="1" />
			</xsd:sequence>
			<xsd:attribute type="xsd:string" name="id" use="required" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="users">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="user" minOccurs="1" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

</xsd:schema>

=== habyb/Java-Advanced/XMLValidateSAX/users.xml
<?xml version="1.0" encoding="UTF-8"?>

<users xmlns="http://www.elasticconcept.com/java/xml"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.elasticconcept.com/java/xml users.xsd">
	
	<user id="1">
		<name>John Doe Fianc√©</name>
		<age>30</age>
		<email>john@xyz.com</email>
	</user>
	
	<user id="2">
		<name>Mary Kate</name>
		<age>20</age>
		<email>mary@xyz.com</email>
	</user>
</users>
